version: '2'

services:
  nginx:
    image: linuxserver/swag:1.7.0-ls7
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Eastern
      - URL=ocvt.club
      - SUBDOMAINS=www,api
      - VALIDATION=http
      - STAGING=true
    volumes:
      - ./nginx.conf:/config/nginx/nginx.conf:ro
      - ./site-confs:/config/nginx/site-confs:ro
    ports:
      - 443:443
      - 80:80
    networks:
      - ocvt-net

  ocvt-api:
    image: ocvt/dolabra:1.0.1
    restart: unless-stopped
    env_file: dolabra.env
    volumes:
      - ./data:/go/src/app/data:rw
    networks:
      - ocvt-net

  ocvt-site:
    image: ocvt/ocvt-site:1.0.1
    restart: unless-stopped
    env_file: ocvt-site.env
    networks:
      - ocvt-net

networks:
  ocvt-net:
