---
# Common
- hosts: ocvt-main
  become: yes
  handlers:
    - import_tasks: handlers.yml
  tasks:
    - name: Install required packages
      yum:
        name:
          - yum-cron #TODO set yum-cron.conf + enable yum-cron service
          - tmux
          - vim
        update_cache: yes

    - name: Install Docker
      command:
        cmd: amazon-linux-extras install -y docker
        creates: /usr/bin/docker
      notify: Start and enable docker

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - debug:
        msg: Clone aws repo to start services
